# Config file for automatic testing at travis-ci.org
sudo: false
language: python
cache: pip
before_install:
- sudo rm -f /etc/boto.cfg
before_script:
- pip install tox

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: pip install -U tox-travis don't know if needed

# Command to run tests, e.g. python setup.py test
script: 
  - tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    # https://github.com/travis-ci/travis-ci/issues/9069
    #- python: 3.7
    #  env: TOXENV=py37
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=docs